name: Arduino Lint
on:
  - push
  - pull_request
jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: arduino/arduino-lint-action
        uses: arduino/arduino-lint-action@v1.0.1
